name: 手动构建并发布（时间版本号）

on:
  workflow_dispatch:  # 手动触发

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许创建Release

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 生成时间版本号（如 v202508221530）
        id: generate_version
        run: |
          echo "VERSION_TAG=v$(date +%Y%m%d%H%M)" >> $GITHUB_ENV  # 环境变量传递版本号

      - name: 安装Node.js（适配旧版本）
        uses: actions/setup-node@v4
        with:
          node-version: '14'  # 兼容项目老旧依赖

      - name: 安装Cordova
        run: npm install -g cordova@10  # 匹配项目中cordova-android降级记录

      - name: 更新配置文件版本号
        run: |
          # 替换config.xml中的版本号（适配Cordova打包）
          sed -i "s/version=\".*\"/version=\"${{ env.VERSION_TAG#v }}\"/g" config.xml
          # 替换package.json中的版本号（可选，确保一致性）
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ env.VERSION_TAG#v }}\"/g" package.json

      - name: 安装项目依赖
        run: |
          npm install  # 根目录依赖
          cd www && npm install  # www目录依赖

      - name: 构建Android Release APK
        run: |
          cordova platform add android@9  # 适配降级后的cordova-android
          cordova build android --release

      - name: 创建GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}  # 标签=时间版本号
          name: 构建版本 ${{ env.VERSION_TAG }}  # Release名称
          files: platforms/android/app/build/outputs/apk/release/*.apk  # 上传APK
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动获取仓库Token
