name: Build and Release Android APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04  # 使用最新的Ubuntu版本
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7  # 最新版本

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3  # 最新版本
        with:
          node-version: 20.x  # 使用最新LTS版本
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: |
          npm install
          npm install -g cordova@12.0.0  # 最新稳定版Cordova

      - name: Set up Java (JDK 21)
        uses: actions/setup-java@v4.2.1  # 最新版本
        with:
          java-version: '21'  # 使用最新LTS版本
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3.2.0  # 最新版本
        with:
          cmdline-tools-version: 11076708  # 最新命令行工具版本
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true
          # 明确指定所需的Android组件，使用最新稳定版本
          packages: |
            tools
            platform-tools
            build-tools;35.0.0
            platforms;android-35
            patcher;v4
            extras;android;m2repository
            extras;google;m2repository

      - name: Configure Android SDK environment
        run: |
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/build-tools/35.0.0" >> $GITHUB_PATH

      - name: Verify Android environment
        run: |
          sdkmanager --version
          adb --version
          aapt2 version

      - name: Prepare Cordova project
        run: |
          chmod +x tools/init.sh
          ./tools/init.sh
          cordova platform remove android
          cordova platform add android@13.0.0  # 最新Android平台
          cordova requirements android

      - name: Build Release APK
        run: |
          cordova build android --release -- --gradleArg=-PcdvBuildMultipleApks=false
          ls -la platforms/android/app/build/outputs/apk/release/

      - name: Sign APK
        if: success()
        run: |
          # 创建签名密钥
          keytool -genkeypair \
            -keystore release.keystore \
            -alias release \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            -dname "CN=Unknown, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown"
          
          # 签名APK
          apksigner sign \
            --ks release.keystore \
            --ks-key-alias release \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
          
          # 重命名签名后的APK
          mv platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
             platforms/android/app/build/outputs/apk/release/app-release-signed.apk

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.8  # 更可靠的release动作
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: platforms/android/app/build/outputs/apk/release/app-release-signed.apk
