name: Build and Release Android APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm install -g cordova@11.0.0

      - name: Set up Java (JDK 11)
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3.2.0
        with:
          cmdline-tools-version: 7583922
          accept-android-sdk-licenses: true
          packages:
            - tools
            - platform-tools
            - build-tools;33.0.1
            - platforms;android-33
            - extras;android;m2repository
            - extras;google;m2repository

      - name: Manually install SDK packages
        run: |
          sdkmanager "tools"
          sdkmanager "platform-tools"
          sdkmanager "build-tools;33.0.1"
          sdkmanager "platforms;android-33"
          sdkmanager "extras;android;m2repository"
          sdkmanager "extras;google;m2repository"
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk

      - name: Configure Android environment
        run: |
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/build-tools/33.0.1" >> $GITHUB_PATH

      - name: Verify environment
        run: |
          sdkmanager --version
          adb --version
          java -version
          cordova --version

      - name: Prepare Cordova project
        run: |
          chmod +x tools/init.sh
          ./tools/init.sh
          cordova platform remove android
          cordova platform add android@10.1.2
          cordova requirements android

      - name: Build Release APK
        run: |
          cordova build android --release -- --gradleArg=-PcdvBuildMultipleApks=false
          ls -la platforms/android/app/build/outputs/apk/release/

      - name: Sign APK
        if: success()
        run: |
          keytool -genkeypair \
            -keystore release.keystore \
            -alias release \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            -dname "CN=Unknown, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown"
          
          apksigner sign \
            --ks release.keystore \
            --ks-key-alias release \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
          
          mv platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
             platforms/android/app/build/outputs/apk/release/app-release-signed.apk

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: platforms/android/app/build/outputs/apk/release/app-release-signed.apk
